import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'de', 'fr', 'es', 'zh_Hans'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? deText = '',
    String? frText = '',
    String? esText = '',
    String? zh_HansText = '',
  }) =>
      [enText, deText, frText, esText, zh_HansText][languageIndex] ?? '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // ProfileSettings
  {
    'fcx17xnl': {
      'en': 'Complete Profile',
      'de': 'Vollständiges Profil',
      'es': 'Perfil completo',
      'fr': 'Profil complet',
      'zh_Hans': '完整简介',
    },
    '50p3dqj6': {
      'en': 'Complete your Profile-Settings',
      'de': 'Vervollständige deine Profileinstellungen',
      'es': 'Complete la configuración de su perfil',
      'fr': 'Complétez vos paramètres de profil',
      'zh_Hans': '完成您的个人资料设置',
    },
    'dkq1ryfg': {
      'en': 'Your information',
      'de': 'Ihre Informationen',
      'es': 'Tu información',
      'fr': 'Vos informations',
      'zh_Hans': '你的资料',
    },
    'xt634rup': {
      'en': 'Your Name',
      'de': 'Ihr Name',
      'es': 'Su nombre',
      'fr': 'votre nom',
      'zh_Hans': '你的名字',
    },
    'zx5xaek7': {
      'en': 'Email',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'svckxjk7': {
      'en': 'Email',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'ka02yxp3': {
      'en': 'Phone',
      'de': 'Telefon',
      'es': 'Teléfono',
      'fr': 'Téléphone',
      'zh_Hans': '电话',
    },
    '58pt8dru': {
      'en': 'Phone',
      'de': 'Telefon',
      'es': 'Teléfono',
      'fr': 'Téléphone',
      'zh_Hans': '电话',
    },
    'oaa48gll': {
      'en': 'Change Adress',
      'de': 'Adresse ändern',
      'es': 'Cambiar dirección',
      'fr': 'Changer d\'adresse',
      'zh_Hans': '更改地址',
    },
    'w9gnwzri': {
      'en': 'Change IT-Skills',
      'de': 'IT-Kenntnisse ändern',
      'es': 'Cambiar las habilidades de TI',
      'fr': 'Changer les compétences informatiques',
      'zh_Hans': '改变 IT 技能',
    },
    'ohebf1ur': {
      'en': 'Change Languages',
      'de': 'Sprachen ändern',
      'es': 'Cambiar idiomas',
      'fr': 'Changer de langue',
      'zh_Hans': '更改语言',
    },
    'e9h4u4e3': {
      'en': 'Save Changes',
      'de': 'Änderungen speichern',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'zh_Hans': '保存更改',
    },
    'yfmi94wv': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // Adress-Settings
  {
    'xvk3q9k4': {
      'en': 'Complete Adress',
      'de': 'Vollständige Adresse',
      'es': 'Dirección completa',
      'fr': 'Adresse complète',
      'zh_Hans': '完整地址',
    },
    'ivwsse2p': {
      'en': 'Complete your adress information',
      'de': 'Vervollständigen Sie Ihre Adressdaten',
      'es': 'Completa los datos de tu dirección',
      'fr': 'Complétez vos informations d\'adresse',
      'zh_Hans': '填写您的地址信息',
    },
    'pqv49jgr': {
      'en': 'Your information',
      'de': 'Ihre Informationen',
      'es': 'Tu información',
      'fr': 'Vos informations',
      'zh_Hans': '你的资料',
    },
    '0e9c64ob': {
      'en': 'Street and Number',
      'de': 'Straße und Nummer',
      'es': 'Calle y número',
      'fr': 'Rue et numéro',
      'zh_Hans': '街道和门牌号',
    },
    '4kvp5cnu': {
      'en': 'Street',
      'de': 'Straße',
      'es': 'Calle',
      'fr': 'Rue',
      'zh_Hans': '街道',
    },
    'vv98yz02': {
      'en': 'Town',
      'de': 'Stadt',
      'es': 'Ciudad',
      'fr': 'Ville',
      'zh_Hans': '镇',
    },
    'tl7vy8f9': {
      'en': 'Town',
      'de': 'Stadt',
      'es': 'Ciudad',
      'fr': 'Ville',
      'zh_Hans': '镇',
    },
    'sqb1k3ec': {
      'en': 'Postal-Code',
      'de': 'Postleitzahl',
      'es': 'Código Postal',
      'fr': 'Code Postal',
      'zh_Hans': '邮政编码',
    },
    'yxwo7j7o': {
      'en': 'Postal-Code',
      'de': 'Postleitzahl',
      'es': 'Código Postal',
      'fr': 'Code Postal',
      'zh_Hans': '邮政编码',
    },
    's6h1wnxo': {
      'en': 'Country',
      'de': 'Land',
      'es': 'País',
      'fr': 'Pays',
      'zh_Hans': '国家',
    },
    '0g14koc1': {
      'en': 'Country',
      'de': 'Land',
      'es': 'País',
      'fr': 'Pays',
      'zh_Hans': '国家',
    },
    'mpk8lics': {
      'en': 'Save Changes',
      'de': 'Änderungen speichern',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'zh_Hans': '保存更改',
    },
    'dr5994wq': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // IT-Skills-Settings
  {
    'th69fh0p': {
      'en': 'Complete IT-Skills',
      'de': 'Umfassende IT-Kenntnisse',
      'es': 'Completas habilidades de TI',
      'fr': 'Compétences informatiques complètes',
      'zh_Hans': '完整的 IT 技能',
    },
    'zwdp76ds': {
      'en': 'Complete your IT-Skills',
      'de': 'Vervollständigen Sie Ihre IT-Kenntnisse',
      'es': 'Complete sus habilidades de TI',
      'fr': 'Complétez vos compétences informatiques',
      'zh_Hans': '完善你的 IT 技能',
    },
    'shhe1ydw': {
      'en': 'Your IT-Skills',
      'de': 'Deine IT-Kenntnisse',
      'es': 'Tus habilidades de TI',
      'fr': 'Vos compétences informatiques',
      'zh_Hans': '您的 IT 技能',
    },
    'o9puwj76': {
      'en': 'Save Changes',
      'de': 'Änderungen speichern',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'zh_Hans': '保存更改',
    },
    'w70117by': {
      'en': 'new IT-Skills ',
      'de': 'neue IT-Kenntnisse',
      'es': 'nuevas habilidades de TI',
      'fr': 'nouvelles compétences informatiques',
      'zh_Hans': '新的 IT 技能',
    },
    'awk15nmc': {
      'en': 'Add IT Skills here',
      'de': 'Fügen Sie hier IT-Kenntnisse hinzu',
      'es': 'Agregue habilidades de TI aquí',
      'fr': 'Ajoutez des compétences informatiques ici',
      'zh_Hans': '在此处添加 IT 技能',
    },
    'ocq5kvbi': {
      'en': 'Add',
      'de': 'Hinzufügen',
      'es': 'Agregar',
      'fr': 'Ajouter',
      'zh_Hans': '添加',
    },
    '5ej9zapx': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // Language-Settings
  {
    '4bq07mgn': {
      'en': 'Complete Languages',
      'de': 'Komplette Sprachen',
      'es': 'Idiomas completos',
      'fr': 'Langues complètes',
      'zh_Hans': '完整语言',
    },
    'whlv0la7': {
      'en': 'Complete your languages',
      'de': 'Vervollständigen Sie Ihre Sprachen',
      'es': 'Completa tus idiomas',
      'fr': 'Complétez vos langues',
      'zh_Hans': '完成你的语言',
    },
    'z797zvs5': {
      'en': 'Your Languages',
      'de': 'Ihre Sprachen',
      'es': 'Tus idiomas',
      'fr': 'Vos langues',
      'zh_Hans': '你的语言',
    },
    '9umukc55': {
      'en': 'Save Changes',
      'de': 'Änderungen speichern',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'zh_Hans': '保存更改',
    },
    'pnbjiyri': {
      'en': 'new Language',
      'de': 'neue Sprache',
      'es': 'nuevo idioma',
      'fr': 'nouveau langage',
      'zh_Hans': '新语言',
    },
    'ujxa03re': {
      'en': 'Add Language here',
      'de': 'Fügen Sie hier eine Sprache hinzu',
      'es': 'Añadir idioma aquí',
      'fr': 'Ajouter une langue ici',
      'zh_Hans': '在此处添加语言',
    },
    'rfcncdh0': {
      'en': 'Add',
      'de': 'Hinzufügen',
      'es': 'Agregar',
      'fr': 'Ajouter',
      'zh_Hans': '添加',
    },
    'pi0dfjv1': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // Customer
  {
    'fwglq52i': {
      'en': 'Name',
      'de': 'Name',
      'es': 'Nombre',
      'fr': 'Nom',
      'zh_Hans': '姓名',
    },
    '6fgimpch': {
      'en': 'Phone',
      'de': 'Telefon',
      'es': 'Teléfono',
      'fr': 'Téléphone',
      'zh_Hans': '电话',
    },
    '1svt6qwg': {
      'en': 'Mail',
      'de': 'Mail',
      'es': 'Correo',
      'fr': 'Mail',
      'zh_Hans': '邮件',
    },
    'igthvfrg': {
      'en': 'Location',
      'de': 'Standort',
      'es': 'Ubicación',
      'fr': 'Emplacement',
      'zh_Hans': '地点',
    },
    'pfk6zl6k': {
      'en': 'GitHub-Link',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    's3b1jvke': {
      'en': 'Themes',
      'de': 'Themen',
      'es': 'Temas',
      'fr': 'Thèmes',
      'zh_Hans': '主题',
    },
    'w9rexsje': {
      'en': 'Languages',
      'de': 'Sprachen',
      'es': 'Idiomas',
      'fr': 'Langues',
      'zh_Hans': '语言',
    },
    '91qmu550': {
      'en': 'Revenue',
      'de': 'Einnahmen',
      'es': 'Ganancia',
      'fr': 'Revenu',
      'zh_Hans': '收入',
    },
    'xf3hox2c': {
      'en': 'Status',
      'de': 'Status',
      'es': 'Estado',
      'fr': 'Statut',
      'zh_Hans': '地位',
    },
    'mzuncnhu': {
      'en': 'Add meeting to user',
      'de': 'Meeting dem Benutzer hinzufügen',
      'es': 'Agregar reunión al usuario',
      'fr': 'Ajouter une réunion à l\'utilisateur',
      'zh_Hans': '向用户添加会议',
    },
    'sm949xko': {
      'en': 'Edit Case',
      'de': 'Fall bearbeiten',
      'es': 'Editar caso',
      'fr': 'Modifier le cas',
      'zh_Hans': '編輯案例',
    },
    '955no1if': {
      'en': 'Date',
      'de': 'Datum',
      'es': 'Fecha',
      'fr': 'Date',
      'zh_Hans': '日期',
    },
    'uwi3huii': {
      'en': 'Duration',
      'de': 'Dauer',
      'es': 'Duración',
      'fr': 'Durée',
      'zh_Hans': '期间',
    },
    '8c86p3v1': {
      'en': 'Costs',
      'de': 'Kosten',
      'es': 'Costos',
      'fr': 'Frais',
      'zh_Hans': '成本',
    },
    'g13pqfbb': {
      'en': 'Supervisor',
      'de': 'Aufsicht',
      'es': 'Supervisor',
      'fr': 'Superviseur',
      'zh_Hans': '导师',
    },
    'w6upyuwo': {
      'en': 'ID: ',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'ip3q1bpk': {
      'en': 'ID:',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    '365ngbkk': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // Main
  {
    '3xmp7l5l': {
      'en': 'bytes Coding',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'ugt68zzx': {
      'en': 'Platform Navigation',
      'de': 'Platform Navigation',
      'es': 'Navegación de plataforma',
      'fr': 'Navigation sur la plateforme',
      'zh_Hans': '平台导航',
    },
    '15s2dq8x': {
      'en': 'Main-Menu',
      'de': 'Hauptmenü',
      'es': 'Menú principal',
      'fr': 'Menu principal',
      'zh_Hans': '主菜单',
    },
    '6g8wo7v3': {
      'en': '12',
      'de': '12',
      'es': '12',
      'fr': '12',
      'zh_Hans': '12',
    },
    'lusq685u': {
      'en': 'Chats',
      'de': 'Chats',
      'es': 'Charlas',
      'fr': 'Discussions',
      'zh_Hans': '聊天',
    },
    '5zyogc9t': {
      'en': '12',
      'de': '12',
      'es': '12',
      'fr': '12',
      'zh_Hans': '12',
    },
    'uc1usyqa': {
      'en': 'Support Tickets',
      'de': 'Support-Tickets',
      'es': 'Boletos de soporte',
      'fr': 'Billets d\'assistance',
      'zh_Hans': '支持票',
    },
    'uuz9xwx4': {
      'en': '12',
      'de': '12',
      'es': '12',
      'fr': '12',
      'zh_Hans': '12',
    },
    '72kdiy21': {
      'en': 'Customer Matching',
      'de': 'Kundenabgleich',
      'es': 'Emparejamiento de clientes',
      'fr': 'Correspondance client',
      'zh_Hans': '客户匹配',
    },
    'dm0y1b6g': {
      'en': 'Role Management',
      'de': 'Rollenverwaltung',
      'es': 'Gestión de roles',
      'fr': 'Gestion des rôles',
      'zh_Hans': '角色管理',
    },
    '4tmi2f8n': {
      'en': 'Employee Billing',
      'de': 'Mitarbeiterabrechnung',
      'es': 'Facturación de empleados',
      'fr': 'Facturation des employés',
      'zh_Hans': '员工账单',
    },
    'dyx62bdw': {
      'en': 'Customers',
      'de': 'Kunden',
      'es': 'Clientes',
      'fr': 'Clients',
      'zh_Hans': '顾客',
    },
    '12tpf17h': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'fr': 'Paramètres',
      'zh_Hans': '设置',
    },
    'xahmx4lz': {
      'en': 'Billing',
      'de': 'Abrechnung',
      'es': 'Facturación',
      'fr': 'Facturation',
      'zh_Hans': '计费',
    },
    'azmu0lbt': {
      'en': 'Members',
      'de': 'Mitglieder',
      'es': 'Miembros',
      'fr': 'Membres',
      'zh_Hans': '成员',
    },
    'v3wuo8gh': {
      'en': 'Light Mode',
      'de': 'Lichtmodus',
      'es': 'Modo de luz',
      'fr': 'Mode lumière',
      'zh_Hans': '灯光模式',
    },
    '1m01zim9': {
      'en': 'Dark Mode',
      'de': 'Dunkler Modus',
      'es': 'Modo oscuro',
      'fr': 'Mode sombre',
      'zh_Hans': '暗黑模式',
    },
    'tmoj32d1': {
      'en': 'Projects Overview',
      'de': 'Projekte Übersicht',
      'es': 'Resumen de proyectos',
      'fr': 'Aperçu des projets',
      'zh_Hans': '项目概况',
    },
    'ohbxki3q': {
      'en': 'Review the details below of all current projects.',
      'de': 'Sehen Sie sich unten die Details aller aktuellen Projekte an.',
      'es':
          'Revise los detalles a continuación de todos los proyectos actuales.',
      'fr': 'Consultez les détails ci-dessous de tous les projets en cours.',
      'zh_Hans': '查看以下所有当前项目的详细信息。',
    },
    'hv1ie1b8': {
      'en': 'Add Customer',
      'de': 'Kunden hinzufügen',
      'es': 'Agregar cliente',
      'fr': 'Ajouter un client',
      'zh_Hans': '添加客户',
    },
    'aaep28x3': {
      'en': 'Add Case',
      'de': 'Fall hinzufügen',
      'es': 'Agregar caso',
      'fr': 'Ajouter un cas',
      'zh_Hans': '添加案例',
    },
    'n9qnpbyi': {
      'en': 'ID#: ',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'xpe9vzmw': {
      'en': 'ID#: ',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'nhxrq5ni': {
      'en': 'ID#: ',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'sntf2ubj': {
      'en': 'ID#: ',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    's9jo3pju': {
      'en': 'Own',
      'de': 'Eigen',
      'es': 'Propio',
      'fr': 'Propre',
      'zh_Hans': '自己的',
    },
    'u27w6351': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // Users
  {
    'lefjjtu5': {
      'en': 'Search for people...',
      'de': 'Suche nach Personen...',
      'es': 'Búsqueda de personas...',
      'fr': 'Recherche de personnes...',
      'zh_Hans': '搜尋人...',
    },
    'm4jj16bz': {
      'en': 'Search for people...',
      'de': 'Suche nach Personen...',
      'es': 'Búsqueda de personas...',
      'fr': 'Recherche de personnes...',
      'zh_Hans': '搜尋人...',
    },
    'j34sl75v': {
      'en': 'Team-Members',
      'de': 'Team-Mitglieder',
      'es': 'Miembros del equipo',
      'fr': 'Membres de l\'équipe',
      'zh_Hans': '团队成员',
    },
    '73o0o7i4': {
      'en': 'All of our Customers & Employees',
      'de': 'Alle unsere Kunden und Mitarbeiter',
      'es': 'Todos nuestros clientes y empleados',
      'fr': 'Tous nos clients et employés',
      'zh_Hans': '我们所有的客户和员工',
    },
    'l72xtc1b': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // CreateCase
  {
    '63tpu80q': {
      'en': 'ID:',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    '91f8nfh0': {
      'en': 'Case ID',
      'de': 'Fall-ID',
      'es': 'Identificación del caso',
      'fr': 'Numéro de cas',
      'zh_Hans': '案例ID',
    },
    'q2qhf2ce': {
      'en': 'Case ID...',
      'de': 'Fall-ID...',
      'es': 'Identificación del caso...',
      'fr': 'Numéro d\'identification du cas...',
      'zh_Hans': '案例ID...',
    },
    'y00zbz7g': {
      'en': 'Title...',
      'de': 'Titel...',
      'es': 'Título...',
      'fr': 'Titre...',
      'zh_Hans': '标题...',
    },
    'eaxq1etl': {
      'en': 'Title...',
      'de': 'Titel...',
      'es': 'Título...',
      'fr': 'Titre...',
      'zh_Hans': '标题...',
    },
    'zrh50pvf': {
      'en': 'Description...',
      'de': 'Beschreibung...',
      'es': 'Descripción...',
      'fr': 'Description...',
      'zh_Hans': '描述...',
    },
    'orutdw07': {
      'en': 'Description...',
      'de': 'Beschreibung...',
      'es': 'Descripción...',
      'fr': 'Description...',
      'zh_Hans': '描述...',
    },
    'zboepkw1': {
      'en': 'Github Link',
      'de': 'Github Link',
      'es': 'Github Link',
      'fr': 'Github Link',
      'zh_Hans': 'Github Link',
    },
    'y2utkbqo': {
      'en': 'GitHub- Link',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    '01kliwsx': {
      'en': 'GitHub- Link',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    '3ymofq1p': {
      'en': 'Themes',
      'de': 'Themen',
      'es': 'Temas',
      'fr': 'Thèmes',
      'zh_Hans': '主题',
    },
    'nh1r0238': {
      'en': 'Option 1',
      'de': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'zh_Hans': '选项1',
    },
    'u3h0qui2': {
      'en': 'Topics',
      'de': 'Themen',
      'es': 'Temas',
      'fr': 'Les sujets',
      'zh_Hans': '主题',
    },
    'h13kg7qr': {
      'en': 'Search for a topic...',
      'de': 'Suche nach einem Thema...',
      'es': 'Busca un tema...',
      'fr': 'Rechercher un sujet...',
      'zh_Hans': '搜索主题...',
    },
    'sx3ty69v': {
      'en': 'Customer',
      'de': 'Kunde',
      'es': 'Cliente',
      'fr': 'Client',
      'zh_Hans': '顾客',
    },
    'osvnesbh': {
      'en': 'Option 1',
      'de': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'zh_Hans': '选项1',
    },
    'psh6ke1p': {
      'en': 'Customer Name',
      'de': 'Kundenname',
      'es': 'Nombre del cliente',
      'fr': 'Nom du client',
      'zh_Hans': '顾客姓名',
    },
    'jfcys0av': {
      'en': 'Search for an user...',
      'de': 'Nach einem Benutzer suchen...',
      'es': 'Buscar un usuario...',
      'fr': 'Rechercher un utilisateur...',
      'zh_Hans': '搜索用户...',
    },
    '1m1enuc4': {
      'en': 'Revenue',
      'de': 'Einnahmen',
      'es': 'Ganancia',
      'fr': 'Revenu',
      'zh_Hans': '收入',
    },
    'imvqflfb': {
      'en': 'Price per hour',
      'de': 'Preis pro Stunde',
      'es': 'Precio por hora',
      'fr': 'Prix ​​par heure',
      'zh_Hans': '每小时价格',
    },
    'zy0j4m21': {
      'en': '50',
      'de': '50',
      'es': '50',
      'fr': '50',
      'zh_Hans': '50',
    },
    'p25f6cpa': {
      'en': 'Add Case',
      'de': 'Fall hinzufügen',
      'es': 'Agregar caso',
      'fr': 'Ajouter un cas',
      'zh_Hans': '添加案例',
    },
    '0rdy80es': {
      'en': 'Create Case',
      'de': 'Fall erstellen',
      'es': 'Crear caso',
      'fr': 'Créer un cas',
      'zh_Hans': '创建案例',
    },
    'brd4f1fu': {
      'en': 'Create a new case with this form',
      'de': 'Erstellen Sie mit diesem Formular einen neuen Fall',
      'es': 'Crear un nuevo caso con este formulario',
      'fr': 'Créez un nouveau dossier avec ce formulaire',
      'zh_Hans': '使用此表单创建新案例',
    },
    'vvddebob': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // auth_2_Create
  {
    '7g15vrub': {
      'en': 'bytes Coding',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'yuf6qyzb': {
      'en': 'Get Started',
      'de': 'Loslegen',
      'es': 'Empezar',
      'fr': 'Commencer',
      'zh_Hans': '立即开始',
    },
    'n8xp8945': {
      'en': 'Create an account by using the form below.',
      'de': 'Erstellen Sie mithilfe des untenstehenden Formulars ein Konto.',
      'es': 'Cree una cuenta utilizando el siguiente formulario.',
      'fr': 'Créez un compte en utilisant le formulaire ci-dessous.',
      'zh_Hans': '使用下面的表格创建一个帐户。',
    },
    'hxdqv67a': {
      'en': 'Email',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'k3t8iv0d': {
      'en': 'Password',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'zh_Hans': '密码',
    },
    '758me7y0': {
      'en': 'Password',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'zh_Hans': '密码',
    },
    'am9thlup': {
      'en': 'Create Account',
      'de': 'Benutzerkonto erstellen',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'zh_Hans': '创建账户',
    },
    'cp9wwxhh': {
      'en': 'Or sign up with',
      'de': 'Oder registrieren Sie sich mit',
      'es': 'O regístrate con',
      'fr': 'Ou inscrivez-vous avec',
      'zh_Hans': '或注册',
    },
    'zohwxmwa': {
      'en': 'Continue with Google',
      'de': 'Weiter mit Google',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'zh_Hans': '继续使用 Google',
    },
    'l8nmxfqe': {
      'en': 'Continue with Apple',
      'de': 'Weiter mit Apple',
      'es': 'Continuar con Apple',
      'fr': 'Continuer avec Apple',
      'zh_Hans': '继续使用 Apple',
    },
    '4o69hz8n': {
      'en': 'Already have an account? ',
      'de': 'Sie haben bereits ein Konto?',
      'es': '¿Ya tienes una cuenta?',
      'fr': 'Vous avez déjà un compte?',
      'zh_Hans': '已有账户？',
    },
    'p5d43lji': {
      'en': 'Sign in here',
      'de': 'Hier anmelden',
      'es': 'Firme aquí',
      'fr': 'Se connecter ici',
      'zh_Hans': '在此登录',
    },
    '9fj3ed5h': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // auth_2_Login
  {
    'b1a1m656': {
      'en': 'bytes Coding',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'wc6vlb88': {
      'en': 'Welcome Back',
      'de': 'Willkommen zurück',
      'es': 'Bienvenido de nuevo',
      'fr': 'Content de te revoir',
      'zh_Hans': '欢迎回来',
    },
    '8yhirh5p': {
      'en': 'Fill out the information below in order to access your account.',
      'de':
          'Füllen Sie die folgenden Informationen aus, um auf Ihr Konto zuzugreifen.',
      'es': 'Complete la información a continuación para acceder a su cuenta.',
      'fr':
          'Remplissez les informations ci-dessous afin d\'accéder à votre compte.',
      'zh_Hans': '填写以下信息以访问您的帐户。',
    },
    '8ucnopf5': {
      'en': 'Email',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'petfhqha': {
      'en': 'Password',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'zh_Hans': '密码',
    },
    'p3xaauvg': {
      'en': 'Sign In',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'zh_Hans': '登入',
    },
    '08btyait': {
      'en': 'Or sign in with',
      'de': 'Oder melden Sie sich an mit',
      'es': 'O inicia sesión con',
      'fr': 'Ou connectez-vous avec',
      'zh_Hans': '或使用以下方式登录',
    },
    'pmg4jacf': {
      'en': 'Continue with Google',
      'de': 'Weiter mit Google',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'zh_Hans': '继续使用 Google',
    },
    'lhcickgn': {
      'en': 'Continue with Apple',
      'de': 'Weiter mit Apple',
      'es': 'Continuar con Apple',
      'fr': 'Continuer avec Apple',
      'zh_Hans': '继续使用 Apple',
    },
    '8pwvx02e': {
      'en': 'Don\'t have an account?  ',
      'de': 'Sie haben noch kein Konto?',
      'es': '¿No tienes una cuenta?',
      'fr': 'Vous n\'avez pas de compte ?',
      'zh_Hans': '沒有帳戶？',
    },
    'mk06lsbv': {
      'en': 'Create Account',
      'de': 'Benutzerkonto erstellen',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'zh_Hans': '创建账户',
    },
    'ak2gtbko': {
      'en': 'Forgot password?',
      'de': 'Passwort vergessen?',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'zh_Hans': '忘记密码？',
    },
    'vf342axe': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // auth_2_ForgotPassword
  {
    '2gddz9zm': {
      'en': 'bytes Coding',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'ngxwdtah': {
      'en': 'Forgot Password',
      'de': 'Passwort vergessen',
      'es': 'Has olvidado tu contraseña',
      'fr': 'Mot de passe oublié',
      'zh_Hans': '忘记密码',
    },
    'rcdhs0gf': {
      'en':
          'Please fill out your email belo in order to recieve a reset password link.',
      'de':
          'Bitte geben Sie unten Ihre E-Mail-Adresse ein, um einen Link zum Zurücksetzen des Passworts zu erhalten.',
      'es':
          'Complete su correo electrónico a continuación para recibir un enlace para restablecer la contraseña.',
      'fr':
          'Veuillez remplir votre e-mail ci-dessous afin de recevoir un lien de réinitialisation du mot de passe.',
      'zh_Hans': '请填写下面的电子邮件以便接收重置密码链接。',
    },
    'mzhbas81': {
      'en': 'Email',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'cw6tl9xj': {
      'en': 'Send Reset Link',
      'de': 'Link zum Zurücksetzen senden',
      'es': 'Enviar enlace de reinicio',
      'fr': 'Envoyer le lien de réinitialisation',
      'zh_Hans': '发送重置链接',
    },
    'wlesa9ou': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // auth_2_createProfile
  {
    'erspxmah': {
      'en': 'bytes Coding',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'x7tuflp8': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // auth_2_Profile
  {
    '3gvgvwg1': {
      'en': 'Your Account',
      'de': 'Ihr Konto',
      'es': 'Su cuenta',
      'fr': 'Votre compte',
      'zh_Hans': '你的帐户',
    },
    'od94gyfg': {
      'en': 'Edit Profile',
      'de': 'Profil bearbeiten',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'zh_Hans': '编辑个人资料',
    },
    '3bqy4rph': {
      'en': 'Edit Adress',
      'de': 'Adresse bearbeiten',
      'es': 'Editar dirección',
      'fr': 'Modifier l\'adresse',
      'zh_Hans': '編輯地址',
    },
    'v8wpgdwz': {
      'en': 'Edit Languages',
      'de': 'Sprachen bearbeiten',
      'es': 'Editar idiomas',
      'fr': 'Modifier les langues',
      'zh_Hans': '编辑语言',
    },
    'k9gh52ok': {
      'en': 'Edit IT-Skills',
      'de': 'IT-Kenntnisse bearbeiten',
      'es': 'Editar habilidades de TI',
      'fr': 'Modifier les compétences informatiques',
      'zh_Hans': '编辑 IT 技能',
    },
    'yf1kh2jt': {
      'en': 'App Settings',
      'de': 'App Einstellungen',
      'es': 'Ajustes de Aplicacion',
      'fr': 'Paramètres de l\'application',
      'zh_Hans': '应用程序设置',
    },
    'z84qmaed': {
      'en': 'Support',
      'de': 'Unterstützung',
      'es': 'Apoyo',
      'fr': 'Soutien',
      'zh_Hans': '支持',
    },
    'dodyl2fx': {
      'en': 'Terms of Service',
      'de': 'Nutzungsbedingungen',
      'es': 'Términos de servicio',
      'fr': 'Conditions d\'utilisation',
      'zh_Hans': '服务条款',
    },
    'zhg4cl4u': {
      'en': 'Log Out',
      'de': 'Ausloggen',
      'es': 'Cerrar sesión',
      'fr': 'Se déconnecter',
      'zh_Hans': '登出',
    },
    'bommisgd': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // auth_2_EditProfile
  {
    'xs06iv32': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // support_TicketList
  {
    '8tf2yxr2': {
      'en': 'Ticket #: ',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'b5m54jpy': {
      'en': 'Support Tickets',
      'de': 'Support-Tickets',
      'es': 'Boletos de soporte',
      'fr': 'Billets d\'assistance',
      'zh_Hans': '支持票',
    },
    'y1cphusm': {
      'en': 'Below are a list of recent tickets created',
      'de': 'Unten finden Sie eine Liste der zuletzt erstellten Tickets',
      'es':
          'A continuación se muestra una lista de tickets creados recientemente.',
      'fr': 'Vous trouverez ci-dessous une liste des tickets récemment créés',
      'zh_Hans': '以下是最近创建的票证列表',
    },
    '8bi66y39': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // support_SubmitTicket
  {
    'aekkeure': {
      'en': 'Ticket-Creation',
      'de': 'Ticket-Erstellung',
      'es': 'Creación de entradas',
      'fr': 'Création de tickets',
      'zh_Hans': '票务创建',
    },
    'th2f4v4n': {
      'en': 'Create a Support-Ticket here',
      'de': 'Hier Support-Ticket erstellen',
      'es': 'Cree un ticket de soporte aquí',
      'fr': 'Créez un ticket de support ici',
      'zh_Hans': '在此创建支持单',
    },
    'vj2kin4a': {
      'en': 'Fill out the form below to submit a ticket.',
      'de':
          'Füllen Sie das untenstehende Formular aus, um ein Ticket einzureichen.',
      'es': 'Complete el siguiente formulario para enviar un ticket.',
      'fr': 'Remplissez le formulaire ci-dessous pour soumettre un ticket.',
      'zh_Hans': '填写下面的表格来提交票证。',
    },
    '8a83o12g': {
      'en': 'Call Us',
      'de': 'Rufen Sie uns an',
      'es': 'Llámanos',
      'fr': 'Appelez-nous',
      'zh_Hans': '致电我们',
    },
    'txl8rzat': {
      'en': 'Email Us',
      'de': 'Schreiben Sie uns eine E-Mail',
      'es': 'Envíanos un correo electrónico',
      'fr': 'Envoyez-nous un email',
      'zh_Hans': '发邮件给我们',
    },
    'ricp38cm': {
      'en': 'What is going on?',
      'de': 'Was ist los?',
      'es': '¿Qué está pasando?',
      'fr': 'Que se passe-t-il?',
      'zh_Hans': '到底是怎么回事？',
    },
    '0l26gje2': {
      'en': 'Short Description of what is going on...',
      'de': 'Kurze Beschreibung dessen, was los ist ...',
      'es': 'Breve descripción de lo que está pasando...',
      'fr': 'Brève description de ce qui se passe...',
      'zh_Hans': '简要描述正在发生的事情...',
    },
    'eyq6jort': {
      'en': 'Choose a priority level',
      'de': 'Wählen Sie eine Prioritätsstufe',
      'es': 'Elija un nivel de prioridad',
      'fr': 'Choisissez un niveau de priorité',
      'zh_Hans': '选择优先级别',
    },
    'nj4gxq7y': {
      'en': 'Emergency',
      'de': 'Notfall',
      'es': 'Emergencia',
      'fr': 'Urgence',
      'zh_Hans': '紧急情况',
    },
    'nxn0qt7g': {
      'en': 'High',
      'de': 'Hoch',
      'es': 'Alto',
      'fr': 'Haut',
      'zh_Hans': '高的',
    },
    '36ar5gt0': {
      'en': 'Medium',
      'de': 'Mittel',
      'es': 'Medio',
      'fr': 'Moyen',
      'zh_Hans': '中等的',
    },
    'xbub19mw': {
      'en': 'Low',
      'de': 'Niedrig',
      'es': 'Bajo',
      'fr': 'Faible',
      'zh_Hans': '低的',
    },
    'udk6s772': {
      'en': 'Low',
      'de': 'Niedrig',
      'es': 'Bajo',
      'fr': 'Faible',
      'zh_Hans': '低的',
    },
    'ngxigtui': {
      'en': 'Upload Screenshot',
      'de': 'Screenshot hochladen',
      'es': 'Cargar captura de pantalla',
      'fr': 'Télécharger une capture d\'écran',
      'zh_Hans': '上传截图',
    },
    '9furp0rw': {
      'en': 'Assign User',
      'de': 'Benutzer zuweisen',
      'es': 'Asignar usuario',
      'fr': 'Attribuer un utilisateur',
      'zh_Hans': '分配用户',
    },
    'zdl3izxa': {
      'en': 'Add User',
      'de': 'Benutzer hinzufügen',
      'es': 'Agregar usuario',
      'fr': 'Ajouter un utilisateur',
      'zh_Hans': '添加用户',
    },
    '0sjmvj9o': {
      'en': 'Submit Ticket',
      'de': 'Ticket übermitteln',
      'es': 'Enviar ticket',
      'fr': 'Envoyer le ticket',
      'zh_Hans': '提交工单',
    },
    'h5odabcw': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // support_TicketDetails
  {
    'mscspqqu': {
      'en': 'Ticket Details',
      'de': 'Ticketdetails',
      'es': 'Detalles del billete',
      'fr': 'Détails du billet',
      'zh_Hans': '票务详情',
    },
    'ss89pb28': {
      'en': 'Ticket #: ',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'istektt5': {
      'en': 'Below are the details of this support ticket.',
      'de': 'Nachfolgend finden Sie die Einzelheiten zu diesem Support-Ticket.',
      'es':
          'A continuación se detallan los detalles de este ticket de soporte.',
      'fr': 'Vous trouverez ci-dessous les détails de ce ticket d\'assistance.',
      'zh_Hans': '以下是此支持票的详细信息。',
    },
    'zuqhc7rn': {
      'en': 'Description',
      'de': 'Beschreibung',
      'es': 'Descripción',
      'fr': 'Description',
      'zh_Hans': '描述',
    },
    '2a7z81xx': {
      'en': 'Submitted on',
      'de': 'Eingereicht am',
      'es': 'Presentado el',
      'fr': 'Soumis le',
      'zh_Hans': '提交日期',
    },
    '3b2i6hgq': {
      'en': 'Last Edited',
      'de': 'Zuletzt bearbeitet',
      'es': 'Última edición',
      'fr': 'Dernière modification',
      'zh_Hans': '最后编辑',
    },
    'h1lawcol': {
      'en': 'Status',
      'de': 'Status',
      'es': 'Estado',
      'fr': 'Statut',
      'zh_Hans': '地位',
    },
    '915sp9a8': {
      'en': 'Pending',
      'de': 'Ausstehend',
      'es': 'Pendiente',
      'fr': 'En attente',
      'zh_Hans': '待办的',
    },
    'zv37t5tt': {
      'en': 'In Progress',
      'de': 'Im Gange',
      'es': 'En curso',
      'fr': 'En cours',
      'zh_Hans': '进行中',
    },
    'fbik18u7': {
      'en': 'Complete',
      'de': 'Vollständig',
      'es': 'Completo',
      'fr': 'Complet',
      'zh_Hans': '完全的',
    },
    'l9ecv4xv': {
      'en': 'Submitted',
      'de': 'Gesendet',
      'es': 'Enviado',
      'fr': 'Soumis',
      'zh_Hans': '已提交',
    },
    '5g50y16u': {
      'en': 'Please select...',
      'de': 'Bitte auswählen...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'zh_Hans': '请选择...',
    },
    '74vmywjv': {
      'en': 'Search for a status...',
      'de': 'Nach einem Status suchen ...',
      'es': 'Buscar un estado...',
      'fr': 'Rechercher un statut...',
      'zh_Hans': '搜索状态...',
    },
    'yy7xpy7w': {
      'en': 'Assigned to',
      'de': 'Zugewiesen an',
      'es': 'Asignado a',
      'fr': 'Assigné à',
      'zh_Hans': '分配给',
    },
    'jvimk02l': {
      'en': 'Submitted By',
      'de': 'Eingereicht von',
      'es': 'Presentado por',
      'fr': 'Proposé par',
      'zh_Hans': '由...所提交',
    },
    'sacl5x8e': {
      'en': 'Assign',
      'de': 'Zuordnen',
      'es': 'Asignar',
      'fr': 'Attribuer',
      'zh_Hans': '分配',
    },
    'x5s786v4': {
      'en': 'Update Ticket',
      'de': 'Ticket aktualisieren',
      'es': 'Boleto de actualización',
      'fr': 'Mettre à jour le ticket',
      'zh_Hans': '更新票证',
    },
    'yqpe5xlu': {
      'en': 'Ticket',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'x6ddm1u4': {
      'en': 'Current Support-Ticket',
      'de': 'Aktuelles Support-Ticket',
      'es': 'Ticket de soporte actual',
      'fr': 'Ticket de support actuel',
      'zh_Hans': '当前支持单',
    },
  },
  // EmployeeBilling
  {
    '8zdbsdy4': {
      'en': 'Customer-Information',
      'de': 'Kundeninformation',
      'es': 'Información al cliente',
      'fr': 'Informations client',
      'zh_Hans': '客户信息',
    },
    '2mghmw6b': {
      'en': 'Below is a summary of your activity',
      'de': 'Nachfolgend finden Sie eine Zusammenfassung Ihrer Aktivitäten',
      'es': 'A continuación se muestra un resumen de su actividad.',
      'fr': 'Ci-dessous un résumé de votre activité',
      'zh_Hans': '以下是您的活动摘要',
    },
    'joipmprf': {
      'en': 'Money Earned',
      'de': 'Verdientes Geld',
      'es': 'Dinero ganado',
      'fr': 'L\'argent gagné',
      'zh_Hans': '赚到的钱',
    },
    'bvrj937a': {
      'en': 'Average Billing',
      'de': 'Durchschnittliche Abrechnung',
      'es': 'Facturación promedio',
      'fr': 'Facturation moyenne',
      'zh_Hans': '平均账单',
    },
    'ucngtba5': {
      'en': 'Total Customers',
      'de': 'Kunden gesamt',
      'es': 'Clientes totales',
      'fr': 'Clients totaux',
      'zh_Hans': '客户总数',
    },
    '72k7zctj': {
      'en': 'Revenue Percentage',
      'de': 'Umsatzprozentsatz',
      'es': 'Porcentaje de ingresos',
      'fr': 'Pourcentage de revenus',
      'zh_Hans': '收入百分比',
    },
    'dbqutbci': {
      'en': 'Customer-Information',
      'de': 'Kundeninformation',
      'es': 'Información al cliente',
      'fr': 'Informations client',
      'zh_Hans': '客户信息',
    },
    'llfx7g5q': {
      'en': 'An overview of your customer jobs.',
      'de': 'Eine Übersicht Ihrer Kundenaufträge.',
      'es': 'Una descripción general de los trabajos de sus clientes.',
      'fr': 'Un aperçu de vos tâches clients.',
      'zh_Hans': '您的客户工作概述。',
    },
    'fxfdsogo': {
      'en': 'current customers',
      'de': 'derzeitige Kunden',
      'es': 'clientes actuales',
      'fr': 'clients actuels',
      'zh_Hans': '现有客户',
    },
    '6l634rov': {
      'en': 'completed customers',
      'de': 'abgeschlossene Kunden',
      'es': 'clientes completados',
      'fr': 'clients complétés',
      'zh_Hans': '已完成的客户',
    },
    '82u69mor': {
      'en': 'Customer-Cases',
      'de': 'Kunden-Cases',
      'es': 'Casos de clientes',
      'fr': 'Cas clients',
      'zh_Hans': '客户案例',
    },
    'fnw01e3l': {
      'en': 'A summary of your current customer-cases',
      'de': 'Eine Zusammenfassung Ihrer aktuellen Kundenfälle',
      'es': 'Un resumen de los casos de sus clientes actuales',
      'fr': 'Un résumé de vos cas clients actuels',
      'zh_Hans': '当前客户案例摘要',
    },
    '21mkfth2': {
      'en': 'ID#: ',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    '9iu97squ': {
      'en': 'Own',
      'de': 'Eigen',
      'es': 'Propio',
      'fr': 'Propre',
      'zh_Hans': '自己的',
    },
    '1xsokerm': {
      'en': 'Customer-Meetings',
      'de': 'Kunden-Meetings',
      'es': 'Reuniones con clientes',
      'fr': 'Rendez-vous clients',
      'zh_Hans': '客户会议',
    },
    'bx7t1x0h': {
      'en': 'A summary of your meetings',
      'de': 'Eine Zusammenfassung Ihrer Meetings',
      'es': 'Un resumen de tus reuniones.',
      'fr': 'Un résumé de vos réunions',
      'zh_Hans': '会议摘要',
    },
    'ymj55p09': {
      'en': 'Date',
      'de': 'Datum',
      'es': 'Fecha',
      'fr': 'Date',
      'zh_Hans': '日期',
    },
    '9jkwcq7p': {
      'en': 'Duration',
      'de': 'Dauer',
      'es': 'Duración',
      'fr': 'Durée',
      'zh_Hans': '期间',
    },
    'o52da1js': {
      'en': 'Costs',
      'de': 'Kosten',
      'es': 'Costos',
      'fr': 'Frais',
      'zh_Hans': '成本',
    },
    'phi510ca': {
      'en': 'Supervisor',
      'de': 'Aufsicht',
      'es': 'Supervisor',
      'fr': 'Superviseur',
      'zh_Hans': '导师',
    },
    'sauzmy7r': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // chat_2_Details
  {
    'fmeem6gz': {
      'en': 'Group Chat',
      'de': 'Gruppenchat',
      'es': 'Grupo de chat',
      'fr': 'Discussion de groupe',
      'zh_Hans': '群聊',
    },
    'z9dcgfkq': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // chat_2_main
  {
    '3nlz1j90': {
      'en': 'Add Chat',
      'de': 'Chat hinzufügen',
      'es': 'Agregar chat',
      'fr': 'Ajouter une discussion',
      'zh_Hans': '添加聊天',
    },
    'j81ilpuq': {
      'en': 'Group Chat',
      'de': 'Gruppenchat',
      'es': 'Grupo de chat',
      'fr': 'Discussion de groupe',
      'zh_Hans': '群聊',
    },
    'oq6hlue0': {
      'en': 'My Chats',
      'de': 'Meine Chats',
      'es': 'Mis Chats',
      'fr': 'Mes discussions',
      'zh_Hans': '我的聊天',
    },
    'qwk0a6ke': {
      'en': 'Below are your chats and group chats',
      'de': 'Unten sind Ihre Chats und Gruppenchats',
      'es': 'A continuación se muestran tus chats y chats grupales.',
      'fr':
          'Vous trouverez ci-dessous vos discussions et discussions de groupe',
      'zh_Hans': '以下是您的聊天和群聊',
    },
    'wfh3loj4': {
      'en': '__',
      'de': '__',
      'es': '__',
      'fr': '__',
      'zh_Hans': '__',
    },
  },
  // chat_2_InviteUsers
  {
    'hopvi9vs': {
      'en': 'Invite Users',
      'de': 'Benutzer einladen',
      'es': 'Invitar usuarios',
      'fr': 'Inviter des utilisateurs',
      'zh_Hans': '邀请用户',
    },
    'ql4fu98g': {
      'en': 'Selected',
      'de': 'Ausgewählt',
      'es': 'Seleccionado',
      'fr': 'Choisi',
      'zh_Hans': '已选定',
    },
    '2b5fgo9t': {
      'en': 'Invite Users',
      'de': 'Benutzer einladen',
      'es': 'Invitar usuarios',
      'fr': 'Inviter des utilisateurs',
      'zh_Hans': '邀请用户',
    },
    'pdl3903c': {
      'en': 'Select users from below to start a chat.',
      'de': 'Wählen Sie unten Benutzer aus, um einen Chat zu starten.',
      'es': 'Seleccione usuarios de abajo para iniciar un chat.',
      'fr':
          'Sélectionnez les utilisateurs ci-dessous pour démarrer une discussion.',
      'zh_Hans': '从下面选择用户开始聊天。',
    },
    'jy4o2t2o': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // image_Details
  {
    'r61wss33': {
      'en': 'Image Details',
      'de': 'Bilddetails',
      'es': 'Detalles de la imagen',
      'fr': 'Détails de l\'image',
      'zh_Hans': '图片细节',
    },
    'itj2r1tk': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // CreateCustomer
  {
    'ebpqrveb': {
      'en': 'Full name',
      'de': 'Vollständiger Name',
      'es': 'Nombre completo',
      'fr': 'Nom et prénom',
      'zh_Hans': '全名',
    },
    'wl53zgkt': {
      'en': 'Name',
      'de': 'Name',
      'es': 'Nombre',
      'fr': 'Nom',
      'zh_Hans': '姓名',
    },
    '1qwq52s2': {
      'en': 'Phone number',
      'de': 'Telefonnummer',
      'es': 'Número de teléfono',
      'fr': 'Numéro de téléphone',
      'zh_Hans': '电话号码',
    },
    'k42rx09i': {
      'en': 'Phone Number',
      'de': 'Telefonnummer',
      'es': 'Número de teléfono',
      'fr': 'Numéro de téléphone',
      'zh_Hans': '电话号码',
    },
    'vdzc35iz': {
      'en': 'E-Mail',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'cu1rz8hq': {
      'en': 'E-Mail',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'w83v5p9g': {
      'en': 'Street',
      'de': 'Straße',
      'es': 'Calle',
      'fr': 'Rue',
      'zh_Hans': '街道',
    },
    'dz8s1veo': {
      'en': 'Street',
      'de': 'Straße',
      'es': 'Calle',
      'fr': 'Rue',
      'zh_Hans': '街道',
    },
    '8m7j9wso': {
      'en': 'City',
      'de': 'Stadt',
      'es': 'Ciudad',
      'fr': 'Ville',
      'zh_Hans': '城市',
    },
    'vl5t2xru': {
      'en': 'City',
      'de': 'Stadt',
      'es': 'Ciudad',
      'fr': 'Ville',
      'zh_Hans': '城市',
    },
    'vkwdzh8z': {
      'en': 'Postal-Code',
      'de': 'Postleitzahl',
      'es': 'Código Postal',
      'fr': 'Code Postal',
      'zh_Hans': '邮政编码',
    },
    'as64pn2v': {
      'en': 'Postal-Code',
      'de': 'Postleitzahl',
      'es': 'Código Postal',
      'fr': 'Code Postal',
      'zh_Hans': '邮政编码',
    },
    'hgyxigwg': {
      'en': 'Country',
      'de': 'Land',
      'es': 'País',
      'fr': 'Pays',
      'zh_Hans': '国家',
    },
    'naeu1u2u': {
      'en': 'Country',
      'de': 'Land',
      'es': 'País',
      'fr': 'Pays',
      'zh_Hans': '国家',
    },
    'qzvdq8bg': {
      'en': 'Languages',
      'de': 'Sprachen',
      'es': 'Idiomas',
      'fr': 'Langues',
      'zh_Hans': '语言',
    },
    'xf9ydg3j': {
      'en': 'Option 1',
      'de': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'zh_Hans': '选项1',
    },
    '7kfa0wi0': {
      'en': 'Customer Languages',
      'de': 'Kundensprachen',
      'es': 'Idiomas del cliente',
      'fr': 'Langues du client',
      'zh_Hans': '客户语言',
    },
    'zwexgz3e': {
      'en': 'Search for a language...',
      'de': 'Suche nach einer Sprache...',
      'es': 'Buscar un idioma...',
      'fr': 'Rechercher une langue...',
      'zh_Hans': '搜索语言...',
    },
    'hb047u9p': {
      'en': 'Add Customer',
      'de': 'Kunden hinzufügen',
      'es': 'Agregar cliente',
      'fr': 'Ajouter un client',
      'zh_Hans': '添加客户',
    },
    'the8au5f': {
      'en': 'Create Customer',
      'de': 'Kunden anlegen',
      'es': 'Crear cliente',
      'fr': 'Créer un client',
      'zh_Hans': '创建客户',
    },
    'ic0u8pqs': {
      'en': 'Create new Customer with this Form',
      'de': 'Erstellen Sie mit diesem Formular einen neuen Kunden',
      'es': 'Crear nuevo Cliente con este Formulario',
      'fr': 'Créer un nouveau client avec ce formulaire',
      'zh_Hans': '使用此表单创建新客户',
    },
    'jx8qgyjd': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // AddMeetingToCustomer
  {
    'fq1mmuz6': {
      'en': 'ID:',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'se7z3zjp': {
      'en': 'ID:',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'et2esaos': {
      'en': 'Option 1',
      'de': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'zh_Hans': '选项1',
    },
    'i5paqfsq': {
      'en': 'Tutor',
      'de': 'Tutor',
      'es': 'Tutor',
      'fr': 'Tuteur',
      'zh_Hans': '导师',
    },
    'ccl67tsf': {
      'en': 'Search for an user...',
      'de': 'Nach einem Benutzer suchen...',
      'es': 'Buscar un usuario...',
      'fr': 'Rechercher un utilisateur...',
      'zh_Hans': '搜索用户...',
    },
    '4zfw8bwq': {
      'en': 'Duration',
      'de': 'Dauer',
      'es': 'Duración',
      'fr': 'Durée',
      'zh_Hans': '期间',
    },
    '0zdzhdgd': {
      'en': '0.0',
      'de': '0,0',
      'es': '0.0',
      'fr': '0,0',
      'zh_Hans': '0.0',
    },
    'cc3dpdox': {
      'en': 'costs',
      'de': 'Kosten',
      'es': 'costos',
      'fr': 'frais',
      'zh_Hans': '成本',
    },
    'dw97hdcg': {
      'en': '0.0',
      'de': '0,0',
      'es': '0.0',
      'fr': '0,0',
      'zh_Hans': '0.0',
    },
    'h3i1xjk3': {
      'en': 'Select Date',
      'de': 'Datum auswählen',
      'es': 'Seleccione fecha',
      'fr': 'Sélectionner une date',
      'zh_Hans': '选择日期',
    },
    'xe9lqz5y': {
      'en': 'Selected Date: ',
      'de': 'Ausgewähltes Datum:',
      'es': 'Fecha seleccionada:',
      'fr': 'Date sélectionnée :',
      'zh_Hans': '選擇日期:',
    },
    'f7685vfe': {
      'en': 'Hello World',
      'de': 'Hallo Welt',
      'es': 'Hola Mundo',
      'fr': 'Bonjour le monde',
      'zh_Hans': '你好世界',
    },
    '0hi0scef': {
      'en': 'Save',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'zh_Hans': '节省',
    },
    '142c9phq': {
      'en': 'Add Meeting',
      'de': 'Meeting hinzufügen',
      'es': 'Agregar reunión',
      'fr': 'Ajouter une réunion',
      'zh_Hans': '添加会议',
    },
    '6ak09n8d': {
      'en': 'Add a meeting to a special customer',
      'de': 'Einem besonderen Kunden ein Meeting hinzufügen',
      'es': 'Agregar una reunión a un cliente especial',
      'fr': 'Ajouter une réunion à un client spécial',
      'zh_Hans': '为特殊客户添加会议',
    },
    'h77ncpzt': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // SideNav
  {
    'an40yt0k': {
      'en': 'Navigation',
      'de': 'Navigation',
      'es': 'Navegación',
      'fr': 'La navigation',
      'zh_Hans': '导航',
    },
    'r60f84h5': {
      'en': 'For navigating between screens',
      'de': 'Zur Navigation zwischen Bildschirmen',
      'es': 'Para navegar entre pantallas',
      'fr': 'Pour naviguer entre les écrans',
      'zh_Hans': '用于屏幕间导航',
    },
    's5ry5cyk': {
      'en': 'bytes Coding',
      'de': 'bytes Coding',
      'es': 'bytes Coding',
      'fr': 'bytes Coding',
      'zh_Hans': 'bytes Coding',
    },
    'naqnbvxd': {
      'en': 'Platform Navigation',
      'de': 'Platform Navigation',
      'es': 'Navegación de plataforma',
      'fr': 'Navigation sur la plateforme',
      'zh_Hans': '平台导航',
    },
    'ryazebh4': {
      'en': 'Main-Menu',
      'de': 'Hauptmenü',
      'es': 'Menú principal',
      'fr': 'Menu principal',
      'zh_Hans': '主菜单',
    },
    'pb71eaaj': {
      'en': '12',
      'de': '12',
      'es': '12',
      'fr': '12',
      'zh_Hans': '12',
    },
    '9q77itrm': {
      'en': 'Chats',
      'de': 'Chats',
      'es': 'Charlas',
      'fr': 'Discussions',
      'zh_Hans': '聊天',
    },
    'zv4sd9zz': {
      'en': '12',
      'de': '12',
      'es': '12',
      'fr': '12',
      'zh_Hans': '12',
    },
    '2xnm6fps': {
      'en': 'Support Tickets',
      'de': 'Support-Tickets',
      'es': 'Boletos de soporte',
      'fr': 'Billets d\'assistance',
      'zh_Hans': '支持票',
    },
    'feent0lc': {
      'en': '12',
      'de': '12',
      'es': '12',
      'fr': '12',
      'zh_Hans': '12',
    },
    '8tlki912': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'fr': 'Paramètres',
      'zh_Hans': '设置',
    },
    '5zra02cb': {
      'en': 'Billing',
      'de': 'Abrechnung',
      'es': 'Facturación',
      'fr': 'Facturation',
      'zh_Hans': '计费',
    },
    'm9ww17s0': {
      'en': 'Members',
      'de': 'Mitglieder',
      'es': 'Miembros',
      'fr': 'Membres',
      'zh_Hans': '成员',
    },
    '12w6659s': {
      'en': 'Role Management',
      'de': 'Rollenverwaltung',
      'es': 'Gestión de roles',
      'fr': 'Gestion des rôles',
      'zh_Hans': '角色管理',
    },
    'uhfmvqwm': {
      'en': 'Customer Matching',
      'de': 'Kundenabgleich',
      'es': 'Emparejamiento de clientes',
      'fr': 'Correspondance client',
      'zh_Hans': '客户匹配',
    },
    'urfpy2ae': {
      'en': 'Employee Billing',
      'de': 'Mitarbeiterabrechnung',
      'es': 'Facturación de empleados',
      'fr': 'Facturation des employés',
      'zh_Hans': '员工账单',
    },
    '565faqzv': {
      'en': 'Customers',
      'de': 'Kunden',
      'es': 'Clientes',
      'fr': 'Clients',
      'zh_Hans': '顾客',
    },
    '411g996a': {
      'en': 'Light Mode',
      'de': 'Lichtmodus',
      'es': 'Modo de luz',
      'fr': 'Mode lumière',
      'zh_Hans': '灯光模式',
    },
    'mc7klcgc': {
      'en': 'Dark Mode',
      'de': 'Dunkler Modus',
      'es': 'Modo oscuro',
      'fr': 'Mode sombre',
      'zh_Hans': '暗黑模式',
    },
    '0qj8uewa': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // CustomerBilling
  {
    'brait1y8': {
      'en': 'Customer-Information',
      'de': 'Kundeninformation',
      'es': 'Información al cliente',
      'fr': 'Informations client',
      'zh_Hans': '客户信息',
    },
    'odno4o2l': {
      'en': 'Below is a summary of your activity',
      'de': 'Nachfolgend finden Sie eine Zusammenfassung Ihrer Aktivitäten',
      'es': 'A continuación se muestra un resumen de su actividad.',
      'fr': 'Ci-dessous un résumé de votre activité',
      'zh_Hans': '以下是您的活动摘要',
    },
    'xxc5wt2v': {
      'en': 'Money Spend',
      'de': 'Geld ausgeben',
      'es': 'Gasto de dinero',
      'fr': 'Dépense d\'argent',
      'zh_Hans': '花钱',
    },
    'xrcnzlbf': {
      'en': 'Average Costs',
      'de': 'Durchschnittliche Kosten',
      'es': 'Costos promedio',
      'fr': 'Coûts moyens',
      'zh_Hans': '平均成本',
    },
    'azw44sx6': {
      'en': 'Total Meetings',
      'de': 'Gesamtzahl der Meetings',
      'es': 'Total de reuniones',
      'fr': 'Total des réunions',
      'zh_Hans': '会议总数',
    },
    'd35fb2ze': {
      'en': 'Customer-Meetings',
      'de': 'Kunden-Meetings',
      'es': 'Reuniones con clientes',
      'fr': 'Rendez-vous clients',
      'zh_Hans': '客户会议',
    },
    '4stawemd': {
      'en': 'A summary of your meetings',
      'de': 'Eine Zusammenfassung Ihrer Meetings',
      'es': 'Un resumen de sus reuniones',
      'fr': 'Un résumé de vos réunions',
      'zh_Hans': '会议摘要',
    },
    '72cuvxfy': {
      'en': 'Date',
      'de': 'Datum',
      'es': 'Fecha',
      'fr': 'Date',
      'zh_Hans': '日期',
    },
    'ff89rf83': {
      'en': 'Duration',
      'de': 'Dauer',
      'es': 'Duración',
      'fr': 'Durée',
      'zh_Hans': '期间',
    },
    '0drowsmc': {
      'en': 'Costs',
      'de': 'Kosten',
      'es': 'Costos',
      'fr': 'Frais',
      'zh_Hans': '成本',
    },
    'libsyzti': {
      'en': 'Supervisor',
      'de': 'Aufsicht',
      'es': 'Supervisor',
      'fr': 'Superviseur',
      'zh_Hans': '导师',
    },
    'cddgguhy': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // ProfileEmployee
  {
    'wnodt0nu': {
      'en': 'Mail',
      'de': 'Mail',
      'es': 'Correo',
      'fr': 'Mail',
      'zh_Hans': '邮件',
    },
    'kmtjql97': {
      'en': 'Call',
      'de': 'Anruf',
      'es': 'Llamar',
      'fr': 'Appel',
      'zh_Hans': '称呼',
    },
    'pu04pfxz': {
      'en': 'User-Description',
      'de': 'Benutzer-Beschreibung',
      'es': 'Descripción de usuario',
      'fr': 'Description de l\'utilisateur',
      'zh_Hans': '用户描述',
    },
    'jxgl8tmv': {
      'en': 'Money Earned',
      'de': 'Verdientes Geld',
      'es': 'Dinero ganado',
      'fr': 'L\'argent gagné',
      'zh_Hans': '赚到的钱',
    },
    '1sovajv3': {
      'en': 'Average Billing',
      'de': 'Durchschnittliche Abrechnung',
      'es': 'Facturación promedio',
      'fr': 'Facturation moyenne',
      'zh_Hans': '平均账单',
    },
    'amq25o7c': {
      'en': 'Total Customers',
      'de': 'Kunden gesamt',
      'es': 'Clientes totales',
      'fr': 'Clients totaux',
      'zh_Hans': '客户总数',
    },
    'lyzzcc02': {
      'en': 'Revenue Percentage',
      'de': 'Umsatzprozentsatz',
      'es': 'Porcentaje de ingresos',
      'fr': 'Pourcentage de revenus',
      'zh_Hans': '收入百分比',
    },
    'j5z2op8x': {
      'en': 'Employee-Information',
      'de': 'Mitarbeiterinformation',
      'es': 'Información del empleado',
      'fr': 'Informations sur les employés',
      'zh_Hans': '员工信息',
    },
    'yv1tophe': {
      'en': 'An overview of their customer jobs.',
      'de': 'Eine Übersicht ihrer Kundenjobs.',
      'es': 'Una visión general de los trabajos de sus clientes.',
      'fr': 'Un aperçu de leurs tâches clients.',
      'zh_Hans': '他们的客户工作概述。',
    },
    'nxmksly7': {
      'en': 'current customers',
      'de': 'derzeitige Kunden',
      'es': 'clientes actuales',
      'fr': 'clients actuels',
      'zh_Hans': '现有客户',
    },
    'jj0tni5e': {
      'en': 'completed customers',
      'de': 'abgeschlossene Kunden',
      'es': 'clientes completados',
      'fr': 'clients complétés',
      'zh_Hans': '已完成的客户',
    },
    'ymhq664h': {
      'en': 'Employee-Skills',
      'de': 'Mitarbeiter-Skills',
      'es': 'Habilidades de los empleados',
      'fr': 'Compétences des employés',
      'zh_Hans': '员工技能',
    },
    '3fkffaue': {
      'en': 'Employee-Languages',
      'de': 'Mitarbeiter-Sprachen',
      'es': 'Idiomas de los empleados',
      'fr': 'Langues des employés',
      'zh_Hans': '员工语言',
    },
    'f49vqwjs': {
      'en': 'Customer-Meetings',
      'de': 'Kunden-Meetings',
      'es': 'Reuniones con clientes',
      'fr': 'Rendez-vous clients',
      'zh_Hans': '客户会议',
    },
    '77i9y8d1': {
      'en': 'A summary of their meetings',
      'de': 'Eine Zusammenfassung ihrer Treffen',
      'es': 'Un resumen de sus reuniones.',
      'fr': 'Un résumé de leurs réunions',
      'zh_Hans': '会议纪要',
    },
    'j8agtzis': {
      'en': 'Date',
      'de': 'Datum',
      'es': 'Fecha',
      'fr': 'Date',
      'zh_Hans': '日期',
    },
    'tn9ygrs2': {
      'en': 'Duration',
      'de': 'Dauer',
      'es': 'Duración',
      'fr': 'Durée',
      'zh_Hans': '期间',
    },
    'fl675kqg': {
      'en': 'Costs',
      'de': 'Kosten',
      'es': 'Costos',
      'fr': 'Frais',
      'zh_Hans': '成本',
    },
    '5tnjst8t': {
      'en': 'Supervisor',
      'de': 'Aufsicht',
      'es': 'Supervisor',
      'fr': 'Superviseur',
      'zh_Hans': '导师',
    },
    '79sv2fvf': {
      'en': 'User Profile',
      'de': 'Benutzerprofil',
      'es': 'Perfil del usuario',
      'fr': 'Profil de l\'utilisateur',
      'zh_Hans': '用户资料',
    },
    'np02awzv': {
      'en': 'Complete selected User Profile',
      'de': 'Ausgewähltes Benutzerprofil vervollständigen',
      'es': 'Completar el perfil de usuario seleccionado',
      'fr': 'Compléter le profil utilisateur sélectionné',
      'zh_Hans': '完成选定的用户个人资料',
    },
    '1byh2jsg': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // ProfileUser
  {
    'm6b8boxn': {
      'en': 'Mail',
      'de': 'Mail',
      'es': 'Correo',
      'fr': 'Mail',
      'zh_Hans': '邮件',
    },
    't8vz9hvc': {
      'en': 'Call',
      'de': 'Anruf',
      'es': 'Llamar',
      'fr': 'Appel',
      'zh_Hans': '称呼',
    },
    '0boaf6k3': {
      'en': 'User-Description',
      'de': 'Benutzer-Beschreibung',
      'es': 'Descripción de usuario',
      'fr': 'Description de l\'utilisateur',
      'zh_Hans': '用户描述',
    },
    '6111v0jh': {
      'en': 'Money Spend',
      'de': 'Geld ausgeben',
      'es': 'Gasto de dinero',
      'fr': 'Dépense d\'argent',
      'zh_Hans': '花钱',
    },
    'w1wt2vr6': {
      'en': 'Average Costs',
      'de': 'Durchschnittliche Kosten',
      'es': 'Costos promedio',
      'fr': 'Coûts moyens',
      'zh_Hans': '平均成本',
    },
    'wxdt7dec': {
      'en': 'Total Meetings',
      'de': 'Gesamtzahl der Meetings',
      'es': 'Total de reuniones',
      'fr': 'Total des réunions',
      'zh_Hans': '会议总数',
    },
    '0wr4a1s4': {
      'en': 'Customer-Skills',
      'de': 'Kunden-Skills',
      'es': 'Habilidades del cliente',
      'fr': 'Compétences client',
      'zh_Hans': '顾客技巧',
    },
    'gzahnh8h': {
      'en': 'Customer-Languages',
      'de': 'Kundensprachen',
      'es': 'Idiomas del cliente',
      'fr': 'Langues du client',
      'zh_Hans': '客户语言',
    },
    'dpos0v43': {
      'en': 'Customer-Meetings',
      'de': 'Kunden-Meetings',
      'es': 'Reuniones con clientes',
      'fr': 'Rendez-vous clients',
      'zh_Hans': '客户会议',
    },
    'cpabnexa': {
      'en': 'A summary of their meetings',
      'de': 'Eine Zusammenfassung ihrer Treffen',
      'es': 'Un resumen de sus reuniones.',
      'fr': 'Un résumé de leurs réunions',
      'zh_Hans': '会议纪要',
    },
    'rtwqlk4h': {
      'en': 'Date',
      'de': 'Datum',
      'es': 'Fecha',
      'fr': 'Date',
      'zh_Hans': '日期',
    },
    '3e8hb6wh': {
      'en': 'Duration',
      'de': 'Dauer',
      'es': 'Duración',
      'fr': 'Durée',
      'zh_Hans': '期间',
    },
    'tmkn04zx': {
      'en': 'Costs',
      'de': 'Kosten',
      'es': 'Costos',
      'fr': 'Frais',
      'zh_Hans': '成本',
    },
    'dt34ieih': {
      'en': 'Supervisor',
      'de': 'Aufsicht',
      'es': 'Supervisor',
      'fr': 'Superviseur',
      'zh_Hans': '导师',
    },
    'ersuo796': {
      'en': 'User Profile',
      'de': 'Benutzerprofil',
      'es': 'Perfil del usuario',
      'fr': 'Profil de l\'utilisateur',
      'zh_Hans': '用户资料',
    },
    'nrav9y19': {
      'en': 'Complete selected User Profile',
      'de': 'Ausgewähltes Benutzerprofil vervollständigen',
      'es': 'Completar el perfil de usuario seleccionado',
      'fr': 'Compléter le profil utilisateur sélectionné',
      'zh_Hans': '完成选定的用户个人资料',
    },
    't6mioyok': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // CustomerMatching
  {
    'kgo53uqy': {
      'en': 'Customer-User Matching',
      'de': 'Kunden-Benutzer-Matching',
      'es': 'Emparejamiento cliente-usuario',
      'fr': 'Correspondance client-utilisateur',
      'zh_Hans': '客户-用户匹配',
    },
    'bp9agn7m': {
      'en': 'Match Customer and User together',
      'de': 'Kunde und Benutzer zusammenbringen',
      'es': 'Unir cliente y usuario',
      'fr': 'Associer le client et l\'utilisateur',
      'zh_Hans': '将客户和用户匹配在一起',
    },
    '0b6181i7': {
      'en': 'Customer',
      'de': 'Kunde',
      'es': 'Cliente',
      'fr': 'Client',
      'zh_Hans': '顾客',
    },
    'qxm3fyf5': {
      'en': 'Option 1',
      'de': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'zh_Hans': '选项1',
    },
    'p1u4kwv6': {
      'en': 'Please select...',
      'de': 'Bitte auswählen...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'zh_Hans': '请选择...',
    },
    'v7plhg0s': {
      'en': 'Search for an user...',
      'de': 'Nach einem Benutzer suchen...',
      'es': 'Buscar un usuario...',
      'fr': 'Rechercher un utilisateur...',
      'zh_Hans': '搜索用户...',
    },
    '478sn2bp': {
      'en': 'User',
      'de': 'Benutzer',
      'es': 'Usuario',
      'fr': 'Utilisateur',
      'zh_Hans': '用户',
    },
    'zdkgd9i2': {
      'en': 'Option 1',
      'de': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'zh_Hans': '选项1',
    },
    'oxhvu5uo': {
      'en': 'Please select...',
      'de': 'Bitte auswählen...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'zh_Hans': '请选择...',
    },
    'w2j7a4li': {
      'en': 'Search for an user...',
      'de': 'Nach einem Benutzer suchen...',
      'es': 'Buscar un usuario...',
      'fr': 'Rechercher un utilisateur...',
      'zh_Hans': '搜索用户...',
    },
    'ofst3i3r': {
      'en': 'Save',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'zh_Hans': '节省',
    },
    'sgcssqgt': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'zh_Hans': '家',
    },
  },
  // ChangeEmployeePercentage
  {
    'j749hjez': {
      'en': 'Option 1',
      'de': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'zh_Hans': '选项1',
    },
    'n8uqn2fk': {
      'en': 'Tutor',
      'de': 'Tutor',
      'es': 'Tutor',
      'fr': 'Tuteur',
      'zh_Hans': '导师',
    },
    '1etm02er': {
      'en': 'Search for an user...',
      'de': 'Nach einem Benutzer suchen...',
      'es': 'Buscar un usuario...',
      'fr': 'Rechercher un utilisateur...',
      'zh_Hans': '搜索用户...',
    },
    'c66jsjsp': {
      'en': 'percentage',
      'de': 'Prozentsatz',
      'es': 'porcentaje',
      'fr': 'pourcentage',
      'zh_Hans': '百分比',
    },
    'yzq82ywb': {
      'en': '0.6',
      'de': '0,6',
      'es': '0,6',
      'fr': '0,6',
      'zh_Hans': '0.6',
    },
    '6a35opug': {
      'en': 'Save',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'zh_Hans': '节省',
    },
    'n9kwvokt': {
      'en': 'Change Employee Percentage',
      'de': 'Mitarbeiteranteil ändern',
      'es': 'Cambiar porcentaje de empleados',
      'fr': 'Modifier le pourcentage d\'employés',
      'zh_Hans': '更改员工百分比',
    },
    'a5i4kjxi': {
      'en': 'Change the percentage the Employee recieves',
      'de': 'Ändern Sie den Prozentsatz, den der Mitarbeiter erhält',
      'es': 'Cambiar el porcentaje que recibe el empleado',
      'fr': 'Modifier le pourcentage que l\'employé reçoit',
      'zh_Hans': '更改员工收到的百分比',
    },
    '6hykvly4': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // AllCustomers
  {
    '0cb2nnht': {
      'en': 'Customers',
      'de': 'Kunden',
      'es': 'Clientes',
      'fr': 'Clients',
      'zh_Hans': '顾客',
    },
    '9bl7c0iu': {
      'en': 'Complete Customer-List',
      'de': 'Komplette Kundenliste',
      'es': 'Lista completa de clientes',
      'fr': 'Liste complète des clients',
      'zh_Hans': '完整的客户名单',
    },
    'iu78xj34': {
      'en': 'List of all Customers',
      'de': 'Liste aller Kunden',
      'es': 'Lista de todos los clientes',
      'fr': 'Liste de tous les clients',
      'zh_Hans': '所有客户列表',
    },
    'm0uzgktb': {
      'en': 'Add Customer',
      'de': 'Kunden hinzufügen',
      'es': 'Agregar cliente',
      'fr': 'Ajouter un client',
      'zh_Hans': '添加客户',
    },
    'fn5cvial': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // RoleManagement
  {
    '7cg8ao71': {
      'en': 'Customer-User Matching',
      'de': 'Kunden-Benutzer-Matching',
      'es': 'Emparejamiento cliente-usuario',
      'fr': 'Correspondance client-utilisateur',
      'zh_Hans': '客户-用户匹配',
    },
    'hpuyn1iy': {
      'en': 'Match the Role and Permissions of the users',
      'de': 'Passen Sie die Rolle und Berechtigungen der Benutzer an',
      'es': 'Haga coincidir el rol y los permisos de los usuarios',
      'fr': 'Faites correspondre le rôle et les autorisations des utilisateurs',
      'zh_Hans': '匹配用户的角色和权限',
    },
    'd8m86qjj': {
      'en': 'Role',
      'de': 'Rolle',
      'es': 'Role',
      'fr': 'Rôle',
      'zh_Hans': '角色',
    },
    '0i081vq2': {
      'en': 'Leitung',
      'de': 'Leitung',
      'es': 'Leitung',
      'fr': 'Leitung',
      'zh_Hans': '利通',
    },
    'hyd0rqkf': {
      'en': 'Mitarbeiter',
      'de': 'Mitarbeiter',
      'es': 'Mitarbeiter',
      'fr': 'Mitarbeiter',
      'zh_Hans': '雇员',
    },
    '7d66ojr1': {
      'en': 'Kunde',
      'de': 'Kunde',
      'es': 'Kunde',
      'fr': 'Kundé',
      'zh_Hans': '昆德',
    },
    's6n2px50': {
      'en': 'Please select...',
      'de': 'Bitte auswählen...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'zh_Hans': '请选择...',
    },
    '8zako0ac': {
      'en': 'Search for a role...',
      'de': 'Suche nach einer Rolle ...',
      'es': 'Busca un rol...',
      'fr': 'Rechercher un rôle...',
      'zh_Hans': '搜索角色...',
    },
    '7izaew0u': {
      'en': 'User',
      'de': 'Benutzer',
      'es': 'Usuario',
      'fr': 'Utilisateur',
      'zh_Hans': '用户',
    },
    '101ho30t': {
      'en': 'Option 1',
      'de': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'zh_Hans': '选项1',
    },
    '3lfjpdzd': {
      'en': 'Please select...',
      'de': 'Bitte auswählen...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'zh_Hans': '请选择...',
    },
    '7t0lr6t9': {
      'en': 'Search for an user...',
      'de': 'Nach einem Benutzer suchen...',
      'es': 'Buscar un usuario...',
      'fr': 'Rechercher un utilisateur...',
      'zh_Hans': '搜索用户...',
    },
    'cg5tzc49': {
      'en': 'Save',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'zh_Hans': '节省',
    },
    'qx78yruu': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // EditCase
  {
    'xik97i4m': {
      'en': 'Title',
      'de': 'Titel',
      'es': 'Título',
      'fr': 'Titre',
      'zh_Hans': '标题',
    },
    'bnh81boa': {
      'en': 'Title...',
      'de': 'Titel...',
      'es': 'Título...',
      'fr': 'Titre...',
      'zh_Hans': '标题...',
    },
    'swr6pd8d': {
      'en': 'Title...',
      'de': 'Titel...',
      'es': 'Título...',
      'fr': 'Titre...',
      'zh_Hans': '标题...',
    },
    'jew392jw': {
      'en': 'Description',
      'de': 'Beschreibung',
      'es': 'Descripción',
      'fr': 'Description',
      'zh_Hans': '描述',
    },
    'jla8sb73': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'fyo6vubk': {
      'en': 'Description',
      'de': 'Beschreibung',
      'es': 'Descripción',
      'fr': 'Description',
      'zh_Hans': '描述',
    },
    'uydg8e62': {
      'en': 'Description',
      'de': 'Beschreibung',
      'es': 'Descripción',
      'fr': 'Description',
      'zh_Hans': '描述',
    },
    'pgz945qy': {
      'en': 'Github',
      'de': 'Github',
      'es': 'GitHub',
      'fr': 'GitHub',
      'zh_Hans': 'Github',
    },
    'cbw85193': {
      'en': 'GitHub-Link',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'gecpmalb': {
      'en': 'GitHub-Link',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'tijh27c2': {
      'en': 'Github-Link',
      'de': 'Github-Link',
      'es': 'Enlace Github',
      'fr': 'Lien Github',
      'zh_Hans': 'Github 链接',
    },
    'ukvtcog7': {
      'en': 'Themes',
      'de': 'Themen',
      'es': 'Temas',
      'fr': 'Thèmes',
      'zh_Hans': '主题',
    },
    'mqoo2ht3': {
      'en': 'Option 1',
      'de': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'zh_Hans': '选项1',
    },
    'u20quxri': {
      'en': 'Topics',
      'de': 'Themen',
      'es': 'Temas',
      'fr': 'Les sujets',
      'zh_Hans': '主题',
    },
    'a4rik57b': {
      'en': 'Search for a topic...',
      'de': 'Suche nach einem Thema...',
      'es': 'Busca un tema...',
      'fr': 'Rechercher un sujet...',
      'zh_Hans': '搜索主题...',
    },
    'e0660ag3': {
      'en': 'Revenue',
      'de': 'Einnahmen',
      'es': 'Ganancia',
      'fr': 'Revenu',
      'zh_Hans': '收入',
    },
    'jif9r69p': {
      'en': 'Revenue',
      'de': 'Einnahmen',
      'es': 'Ganancia',
      'fr': 'Revenu',
      'zh_Hans': '收入',
    },
    '2jz5dk2a': {
      'en': 'Price',
      'de': 'Preis',
      'es': 'Precio',
      'fr': 'Prix',
      'zh_Hans': '价格',
    },
    '4kk0zsz3': {
      'en': 'Customer Name',
      'de': 'Kundenname',
      'es': 'Nombre del cliente',
      'fr': 'Nom du client',
      'zh_Hans': '顾客姓名',
    },
    'q3cw3e2u': {
      'en': 'Option 1',
      'de': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'zh_Hans': '选项1',
    },
    'q2ma1w3x': {
      'en': 'Customer Name',
      'de': 'Kundenname',
      'es': 'Nombre del cliente',
      'fr': 'Nom du client',
      'zh_Hans': '顾客姓名',
    },
    '6nsyd1pt': {
      'en': 'Search for an user...',
      'de': 'Nach einem Benutzer suchen...',
      'es': 'Buscar un usuario...',
      'fr': 'Rechercher un utilisateur...',
      'zh_Hans': '搜索用户...',
    },
    '5t6xxn6o': {
      'en': 'Save',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'zh_Hans': '节省',
    },
    'qmta97d7': {
      'en': 'ID: ',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'ukketqor': {
      'en': 'ID:',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'giqvfw1f': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // EditCustomer
  {
    'yma8b9to': {
      'en': 'Full name',
      'de': 'Vollständiger Name',
      'es': 'Nombre completo',
      'fr': 'Nom et prénom',
      'zh_Hans': '全名',
    },
    '3815prlo': {
      'en': 'Name',
      'de': 'Name',
      'es': 'Nombre',
      'fr': 'Nom',
      'zh_Hans': '姓名',
    },
    'wipky3mf': {
      'en': 'Phone number',
      'de': 'Telefonnummer',
      'es': 'Número de teléfono',
      'fr': 'Numéro de téléphone',
      'zh_Hans': '电话号码',
    },
    'i9ekz8ml': {
      'en': 'Phone Number',
      'de': 'Telefonnummer',
      'es': 'Número de teléfono',
      'fr': 'Numéro de téléphone',
      'zh_Hans': '电话号码',
    },
    'q8ftjy4e': {
      'en': 'E-Mail',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'jgeclrna': {
      'en': 'E-Mail',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'c50gx8rc': {
      'en': 'Street',
      'de': 'Straße',
      'es': 'Calle',
      'fr': 'Rue',
      'zh_Hans': '街道',
    },
    'v37jjend': {
      'en': 'Street',
      'de': 'Straße',
      'es': 'Calle',
      'fr': 'Rue',
      'zh_Hans': '街道',
    },
    'tzug8jlu': {
      'en': 'City',
      'de': 'Stadt',
      'es': 'Ciudad',
      'fr': 'Ville',
      'zh_Hans': '城市',
    },
    'hqnc2guy': {
      'en': 'City',
      'de': 'Stadt',
      'es': 'Ciudad',
      'fr': 'Ville',
      'zh_Hans': '城市',
    },
    '69i5j1xm': {
      'en': 'Postal-Code',
      'de': 'Postleitzahl',
      'es': 'Código Postal',
      'fr': 'Code Postal',
      'zh_Hans': '邮政编码',
    },
    'hswr904i': {
      'en': 'Postal-Code',
      'de': 'Postleitzahl',
      'es': 'Código Postal',
      'fr': 'Code Postal',
      'zh_Hans': '邮政编码',
    },
    't8mfivzm': {
      'en': 'Country',
      'de': 'Land',
      'es': 'País',
      'fr': 'Pays',
      'zh_Hans': '国家',
    },
    'gmxp1212': {
      'en': 'Country',
      'de': 'Land',
      'es': 'País',
      'fr': 'Pays',
      'zh_Hans': '国家',
    },
    'hmk4k09k': {
      'en': 'Languages',
      'de': 'Sprachen',
      'es': 'Idiomas',
      'fr': 'Langues',
      'zh_Hans': '语言',
    },
    'dpu6rl4e': {
      'en': 'Option 1',
      'de': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'zh_Hans': '选项1',
    },
    '62nvphkd': {
      'en': 'Customer Languages',
      'de': 'Kundensprachen',
      'es': 'Idiomas del cliente',
      'fr': 'Langues du client',
      'zh_Hans': '客户语言',
    },
    'beeg1rl4': {
      'en': 'Search for a language...',
      'de': 'Suche nach einer Sprache...',
      'es': 'Buscar un idioma...',
      'fr': 'Rechercher une langue...',
      'zh_Hans': '搜索语言...',
    },
    'la0zinmb': {
      'en': 'Save Customer',
      'de': 'Kunden speichern',
      'es': 'Guardar cliente',
      'fr': 'Enregistrer le client',
      'zh_Hans': '保存客户',
    },
    '7wjp85ls': {
      'en': 'Edit Customer',
      'de': 'Kunden bearbeiten',
      'es': 'Editar cliente',
      'fr': 'Modifier le client',
      'zh_Hans': '編輯客戶',
    },
    'gxvsleyb': {
      'en': 'Edit existing Customer with this Form',
      'de': 'Bearbeiten Sie bestehende Kunden mit diesem Formular',
      'es': 'Editar cliente existente con este formulario',
      'fr': 'Modifier un client existant avec ce formulaire',
      'zh_Hans': '使用此表单编辑现有客户',
    },
    'g5jy5gbr': {
      'en': 'Home',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // editProfile_auth_2
  {
    'i42hhvws': {
      'en': 'Adjust the content below to update your profile.',
      'de': 'Passen Sie den Inhalt unten an, um Ihr Profil zu aktualisieren.',
      'es': 'Ajuste el contenido a continuación para actualizar su perfil.',
      'fr': 'Ajustez le contenu ci-dessous pour mettre à jour votre profil.',
      'zh_Hans': '调整下面的内容来更新您的个人资料。',
    },
    'cb6me508': {
      'en': 'Change Photo',
      'de': 'Foto ändern',
      'es': 'Cambiar foto',
      'fr': 'Changer la photo',
      'zh_Hans': '更改照片',
    },
    'kzae2g7n': {
      'en': 'Full Name',
      'de': 'Vollständiger Name',
      'es': 'Nombre completo',
      'fr': 'Nom et prénom',
      'zh_Hans': '全名',
    },
    '7vgor3b8': {
      'en': 'Your full name...',
      'de': 'Ihr vollständiger Name...',
      'es': 'Tu nombre completo...',
      'fr': 'Ton nom complet...',
      'zh_Hans': '你的全名...',
    },
    'zmpduv5f': {
      'en': 'Phone-Number',
      'de': 'Telefonnummer',
      'es': 'Número de teléfono',
      'fr': 'Numéro de téléphone',
      'zh_Hans': '电话号码',
    },
    'ylu1rmoi': {
      'en': 'Your Phone-Number...',
      'de': 'Deine Telefonnummer...',
      'es': 'Su número de teléfono...',
      'fr': 'Votre numéro de téléphone...',
      'zh_Hans': '你的电话号码...',
    },
    '9kyh4fuc': {
      'en': 'Email-Adress',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse email',
      'zh_Hans': '邮箱地址',
    },
    '1pkkrkac': {
      'en': 'Your Phone-Number...',
      'de': 'Deine Telefonnummer...',
      'es': 'Su número de teléfono...',
      'fr': 'Votre numéro de téléphone...',
      'zh_Hans': '你的电话号码...',
    },
    'kmiy5qxl': {
      'en': 'User Role',
      'de': 'Benutzer-Rolle',
      'es': 'Rol del usuario',
      'fr': 'Rôle d\'utilisateur',
      'zh_Hans': '用户角色',
    },
    'wkjljldr': {
      'en': 'Your role...',
      'de': 'Deine Rolle...',
      'es': 'Tu rol...',
      'fr': 'Ton rôle...',
      'zh_Hans': '你的角色...',
    },
    'mv1hv80o': {
      'en': 'Short Description',
      'de': 'kurze Beschreibung',
      'es': 'Breve descripción',
      'fr': 'brève description',
      'zh_Hans': '简短的介绍',
    },
    'bc8lb6wd': {
      'en': 'A little about you...',
      'de': 'Ein bisschen über Sie …',
      'es': 'Un poco sobre ti...',
      'fr': 'Un peu de toi...',
      'zh_Hans': '关于您一些信息...',
    },
  },
  // setPriority_Menu
  {
    '4g1xmiy1': {
      'en': 'Set Priority Level',
      'de': 'Prioritätsstufe festlegen',
      'es': 'Establecer nivel de prioridad',
      'fr': 'Définir le niveau de priorité',
      'zh_Hans': '设置优先级',
    },
    'ceeouso2': {
      'en': 'Emergency',
      'de': 'Notfall',
      'es': 'Emergencia',
      'fr': 'Urgence',
      'zh_Hans': '紧急情况',
    },
    'jnz7a7nx': {
      'en': 'High',
      'de': 'Hoch',
      'es': 'Alto',
      'fr': 'Haut',
      'zh_Hans': '高的',
    },
    'oorxhq9x': {
      'en': 'Medium',
      'de': 'Mittel',
      'es': 'Medio',
      'fr': 'Moyen',
      'zh_Hans': '中等的',
    },
    'na0320sa': {
      'en': 'Low',
      'de': 'Niedrig',
      'es': 'Bajo',
      'fr': 'Faible',
      'zh_Hans': '低的',
    },
  },
  // user_ListSmall
  {
    '2lghugn7': {
      'en': 'ME',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // user_List
  {
    'c7r5aq7h': {
      'en': 'Assign User',
      'de': 'Benutzer zuweisen',
      'es': 'Asignar usuario',
      'fr': 'Attribuer un utilisateur',
      'zh_Hans': '分配用户',
    },
    '1fert8cu': {
      'en': 'Select a user from the list below to continue.',
      'de':
          'Wählen Sie einen Benutzer aus der Liste unten aus, um fortzufahren.',
      'es': 'Seleccione un usuario de la lista a continuación para continuar.',
      'fr':
          'Sélectionnez un utilisateur dans la liste ci-dessous pour continuer.',
      'zh_Hans': '从下面的列表中选择一个用户以继续。',
    },
    't9l5esbd': {
      'en': 'Close',
      'de': 'Schließen',
      'es': 'Cerca',
      'fr': 'Fermer',
      'zh_Hans': '关闭',
    },
  },
  // chat_DetailsOverlay
  {
    'a0loq5a6': {
      'en': 'Group Chat ID: ',
      'de': 'Gruppenchat-ID:',
      'es': 'ID de chat grupal:',
      'fr': 'Identifiant de discussion de groupe :',
      'zh_Hans': '群聊ID：',
    },
    'hspne3ym': {
      'en': 'In this chat',
      'de': 'In diesem Chat',
      'es': 'en esta charla',
      'fr': 'Dans cette discussion',
      'zh_Hans': '在此聊天中',
    },
    '50akzqka': {
      'en': 'Close',
      'de': 'Schließen',
      'es': 'Cerca',
      'fr': 'Fermer',
      'zh_Hans': '关闭',
    },
  },
  // chat_ThreadComponent
  {
    'gj24j4e2': {
      'en': 'Start typing here...',
      'de': 'Beginnen Sie hier mit der Eingabe ...',
      'es': 'Empieza a escribir aquí...',
      'fr': 'Commencez à taper ici...',
      'zh_Hans': '从这里开始输入...',
    },
    'ur37thf2': {
      'en': 'You must enter a message...',
      'de': 'Sie müssen eine Nachricht eingeben...',
      'es': 'Debes ingresar un mensaje...',
      'fr': 'Vous devez saisir un message...',
      'zh_Hans': '您必须输入一条消息...',
    },
    '907lm1aq': {
      'en': 'Please choose an option from the dropdown',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste',
      'es': 'Por favor elija una opción del menú desplegable',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'zh_Hans': '请从下拉列表中选择一个选项',
    },
  },
  // user_ListSmall_1
  {
    'fh4ei39y': {
      'en': 'ME',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
  // deleteDialog
  {
    '3q0utb1e': {
      'en': 'Options',
      'de': 'Optionen',
      'es': 'Opciones',
      'fr': 'Possibilités',
      'zh_Hans': '选项',
    },
    '73scs9a0': {
      'en': 'Invite Users',
      'de': 'Benutzer einladen',
      'es': 'Invitar usuarios',
      'fr': 'Inviter des utilisateurs',
      'zh_Hans': '邀请用户',
    },
    'av9xz4qx': {
      'en': 'Delete Chat',
      'de': 'Chat löschen',
      'es': 'Eliminar chat',
      'fr': 'Supprimer le chat',
      'zh_Hans': '删除聊天',
    },
    '41tv38n3': {
      'en': 'Confirm Delete',
      'de': 'Löschen bestätigen',
      'es': 'Confirmar eliminación',
      'fr': 'Confirmation de la suppression',
      'zh_Hans': '确认删除',
    },
    's2cbswob': {
      'en': 'You can\'t undo this action.',
      'de': 'Sie können diese Aktion nicht rückgängig machen.',
      'es': 'No puedes deshacer esta acción.',
      'fr': 'Vous ne pouvez pas annuler cette action.',
      'zh_Hans': '您无法撤消此操作。',
    },
    'z54qbopv': {
      'en': 'Delete',
      'de': 'Löschen',
      'es': 'Borrar',
      'fr': 'Supprimer',
      'zh_Hans': '删除',
    },
  },
  // Miscellaneous
  {
    'b7nmo9h5': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'xmayfjdy': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'rreotz6t': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    '4hucjyt3': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'pe8bwhny': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'ayl7ml95': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'cj4pi052': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'p3lm87a3': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'hac7gowh': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'hq7117qt': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'iej24wiy': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    '4dk1neen': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'oymp1cmr': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'tezxva0s': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    '3fjb95pu': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'ybkbd0h9': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'tsufngwo': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    '0uulr27y': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'lieon019': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'waotbjhx': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'pbn6f25j': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    '804gd7i9': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'j4z3yl1s': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    '525aerw5': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'xm7jo5yr': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'guzgv3lj': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'vodnos5o': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
    'fwchmphj': {
      'en': '',
      'de': '',
      'es': '',
      'fr': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
